production:
  adapter: postgresql
  encoding: unicode
  database: symantec_rails_production
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: symantec_rails_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: symantec_rails_test
  pool: 5
